service: zendesk-backend

provider:
  name: aws
  runtime: python3.7

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:*
      Resource: "arn:aws:ssm:us-east-1:*:*"

functions:
  getTickets:
    handler: handler.get_tickets
    events:
     - http:
         path: tickets
         method: post
         cors: true
  getTicket:
    handler: handler.get_ticket_by_id
    events:
     - http:
         path: tickets/{id}
         method: get
         cors: true
